# Generated by Django 3.0.3 on 2020-08-12 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('discharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('husband_name', models.CharField(max_length=200)),
                ('diagnosis', models.TextField()),
                ('procedure', models.CharField(max_length=256)),
                ('per_op', models.TextField()),
                ('baby_details', models.TextField()),
                ('hospital_stay', models.CharField(max_length=256)),
                ('advice_on_discharge', models.CharField(max_length=256)),
                ('follow_up', models.CharField(blank=True, default='', max_length=256)),
                ('comment', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drug_dostage_time', models.ManyToManyField(to='basic_app.DrugDosageTime')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Patient')),
                ('precaution', models.ManyToManyField(to='basic_app.Precaution')),
            ],
            options={
                'db_table': 'DischargeSummary',
            },
        ),
        migrations.AddField(
            model_name='previousreport',
            name='blood_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.BloodGroup'),
        ),
    ]
