# Generated by Django 3.0.3 on 2020-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200812_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousreport',
            name='hbs_ag',
            field=models.CharField(choices=[('+ve', '+ve'), ('-ve', '-ve'), ('neutral', 'Neutral')], max_length=10),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hcv',
            field=models.CharField(choices=[('+ve', '+ve'), ('-ve', '-ve'), ('neutral', 'Neutral')], max_length=10),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hiv',
            field=models.CharField(choices=[('+ve', '+ve'), ('-ve', '-ve'), ('neutral', 'Neutral')], max_length=10),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='vdrl',
            field=models.CharField(choices=[('+ve', '+ve'), ('-ve', '-ve'), ('neutral', 'Neutral')], max_length=10),
        ),
    ]
