# Generated by Django 3.0.3 on 2020-08-12 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200812_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDosageTimeDischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Dosage')),
                ('drug', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Patient')),
                ('time', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Time')),
            ],
            options={
                'db_table': 'DrugDosageTimeDischarge',
            },
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='drug_dostage_time',
            field=models.ManyToManyField(to='basic_app.DrugDosageTimeDischarge'),
        ),
    ]
