# Generated by Django 3.0.3 on 2020-08-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200812_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargesummary',
            old_name='drug_dostage_time',
            new_name='drug_dostage_time_discharge',
        ),
    ]
