# Generated by Django 3.0.3 on 2020-08-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20200813_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyform',
            name='chief_complaints',
            field=models.ManyToManyField(blank=True, to='basic_app.ChiefComplaint'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='menstrual',
            field=models.ManyToManyField(blank=True, to='basic_app.Menstrual'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='obsteric_histroy',
            field=models.ManyToManyField(blank=True, to='basic_app.ObstericHistroy'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='past_history',
            field=models.ManyToManyField(blank=True, to='basic_app.PastHistory'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='treatment_history',
            field=models.ManyToManyField(blank=True, to='basic_app.TreatmentHistory'),
        ),
    ]
