# Generated by Django 3.0.3 on 2020-08-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20200813_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiefcomplaint',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dosage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='menstrual',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='obsterichistroy',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='pasthistory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='postivenegative',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='precaution',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='treatmenthistory',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='drug_dostage_time_discharge',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='drug_dostage_time',
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='doa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='dod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drugdosagetime',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.Prescription'),
        ),
        migrations.AddField(
            model_name='drugdosagetimedischarge',
            name='discharge_summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basic_app.DischargeSummary'),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='advice_on_discharge',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='baby_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='hospital_stay',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='husband_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='per_op',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='precaution',
            field=models.ManyToManyField(blank=True, to='basic_app.Precaution'),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='procedure',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, to='basic_app.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='investigation',
            field=models.ManyToManyField(blank=True, to='basic_app.Investigation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='precaution',
            field=models.ManyToManyField(blank=True, to='basic_app.Precaution'),
        ),
    ]
