# Generated by Django 3.0.3 on 2020-08-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20200822_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalexamination',
            old_name='fms',
            new_name='fhs',
        ),
        migrations.AlterField(
            model_name='drugdosagetime',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Prescription'),
        ),
        migrations.AlterField(
            model_name='drugdosagetimedischarge',
            name='discharge_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.DischargeSummary'),
        ),
    ]
