# Generated by Django 3.0.3 on 2020-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20200813_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyform',
            name='obsteric_histroy',
        ),
        migrations.AlterField(
            model_name='historyform',
            name='chief_complaints',
            field=models.ManyToManyField(blank=True, to='basic_app.ChiefComplaint'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='menstrual',
            field=models.ManyToManyField(blank=True, default='', to='basic_app.Menstrual'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='past_history',
            field=models.ManyToManyField(blank=True, default='', to='basic_app.PastHistory'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='treatment_history',
            field=models.ManyToManyField(blank=True, default='', to='basic_app.TreatmentHistory'),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='blood_group_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='bs_f_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='bs_pp_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='bt_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='chest_x_ray_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='ct_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='ecg_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hb_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hbs_ag_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hcv_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='hiv_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='mri_ct_scan_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='platelet_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='s_tsh_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='ur_m_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='previousreport',
            name='usg_date',
            field=models.DateField(blank=True, default='1990-10-10', null=True),
        ),
    ]
