# Generated by Django 3.0.3 on 2020-08-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20200814_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyform',
            name='obsteric_histroy',
            field=models.ManyToManyField(blank=True, default='', to='basic_app.ObstericHistroy'),
        ),
    ]
