# Generated by Django 3.0.3 on 2020-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_historyform_obsteric_histroy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiefcomplaint',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dosage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='menstrual',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='obsterichistroy',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='pasthistory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='postivenegative',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='precaution',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='treatmenthistory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='historyform',
            name='menstrual',
            field=models.ManyToManyField(blank=True, to='basic_app.Menstrual'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='obsteric_histroy',
            field=models.ManyToManyField(blank=True, to='basic_app.ObstericHistroy'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='past_history',
            field=models.ManyToManyField(blank=True, to='basic_app.PastHistory'),
        ),
        migrations.AlterField(
            model_name='historyform',
            name='treatment_history',
            field=models.ManyToManyField(blank=True, to='basic_app.TreatmentHistory'),
        ),
    ]
